import "./globals.css";
import { Open_Sans } from 'next/font/google'

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={openSans.className}>
      <head />
      <body className="antialiased">{children}</body>
    </html>
  );
}
