import "../lib/fontawesome"; // 👈 Import before any UI that uses icons
import "./globals.css";
import './embla.css'
import './base.css'
import { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import Providers from "../context/ReactQueryProvider";

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body className={`antialiased ${openSans.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
